// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdbaoomwhuiztjoazagd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkYmFvb213aHVpenRqb2F6YWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTI3MzEsImV4cCI6MjA2MTUyODczMX0.iNYeY21EzHT838cxScUgfnYO9h9xSPvJRpMbd0RTHWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);